title: Savchenko Physics Problems Solutions
email: aliaksandr@savchenkosolutions.com
description: "Solutions for Savchenko Problems in Physics"
baseurl: "" # Leave this blank for root directory hosting
url: "https://yoursite.com" # Update with your site URL
author: Aliaksandr Melnichenka

# Optional settings
paginate: 5
theme: minima # Change theme if needed
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
